### ISSUE TITLE
Resolve test_iteration_end()

### ISSUE THREAD

**Issue by anushka255** [walruscorp/walrus#9]
Update the country class so that the iteration raises the StopIteration error when each item of country is iterated through.

**Comment by vineetbansal** [comment]
There's got to be other bad side effects of returning a new object of the same class instead of a new object of an iterator-on-the-original-object class that we're not capturing in our tests. It might be interesting to write other test(s) that exposes these side-effects in a more straightforward way.

**Comment by anushka255** [comment]
Created a different iterator class and removed the test_iteration_end() class entirely because the next() iterator doesn't work anymore. Do you still want me to create a different class with an iterator to test these side effects?

**Comment by vineetbansal** [comment]
Thanks!
